project_name: "testing_financial_agent"

# Provider Configuration
provider: "openai"  # Options: "openai", "nvidia", "ollama"

# OpenAI Configuration
openai_models:
  orchestrator:
    provider: openai
    model: gpt-4
    description: "Primary orchestrator for coordinating between different components"
    prompt_handler: "apolanco3225/prompt_orchestrator_agent"
    temperature: 0
    agent_name: "orchestrator"

  company_researcher:
    provider: openai
    model: gpt-4
    description: "Specialized in company research and analysis"
    prompt_handler: "apolanco3225/prompt_company_researcher_agent"
    temperature: 0
    agent_name: "company_researcher"

  portfolio_manager:
    provider: openai
    model: gpt-4
    description: "Manages portfolio composition and investment strategies"
    prompt_handler: "apolanco3225/prompt_portfolio_manager_agent"
    temperature: 0
    agent_name: "portfolio_manager"

  financial_analyst:
    provider: openai
    model: gpt-4
    description: "Performs detailed financial analysis and forecasting"
    prompt_handler: "apolanco3225/prompt_financial_analyst_agent"
    temperature: 0
    agent_name: "financial_analyst"

# NVIDIA Configuration
nvidia_models:
  orchestrator:
    provider: nvidia
    model: nv-mistralai/mistral-nemo-12b-instruct
    description: "Primary orchestrator for coordinating between different components"
    prompt_handler: "apolanco3225/prompt_orchestrator_agent"
    temperature: 0
    agent_name: "orchestrator"

  company_researcher:
    provider: nvidia
    model: nv-mistralai/mistral-nemo-12b-instruct
    description: "Specialized in company research and analysis"
    prompt_handler: "apolanco3225/prompt_company_researcher_agent"
    temperature: 0
    agent_name: "company_researcher"

  portfolio_manager:
    provider: nvidia
    model: nv-mistralai/mistral-nemo-12b-instruct
    description: "Manages portfolio composition and investment strategies"
    prompt_handler: "apolanco3225/prompt_portfolio_manager_agent"
    temperature: 0
    agent_name: "portfolio_manager"

  financial_analyst:
    provider: nvidia
    model: nv-mistralai/mistral-nemo-12b-instruct
    description: "Performs detailed financial analysis and forecasting"
    prompt_handler: "apolanco3225/prompt_financial_analyst_agent"
    temperature: 0
    agent_name: "financial_analyst"

# Ollama Configuration
ollama_models:
  orchestrator:
    provider: ollama
    model: llama2
    description: "Primary orchestrator for coordinating between different components"
    prompt_handler: "apolanco3225/prompt_orchestrator_agent"
    temperature: 0
    agent_name: "orchestrator"

  company_researcher:
    provider: ollama
    model: llama2
    description: "Specialized in company research and analysis"
    prompt_handler: "apolanco3225/prompt_company_researcher_agent"
    temperature: 0
    agent_name: "company_researcher"

  portfolio_manager:
    provider: ollama
    model: llama2
    description: "Manages portfolio composition and investment strategies"
    prompt_handler: "apolanco3225/prompt_portfolio_manager_agent"
    temperature: 0
    agent_name: "portfolio_manager"

  financial_analyst:
    provider: ollama
    model: llama2
    description: "Performs detailed financial analysis and forecasting"
    prompt_handler: "apolanco3225/prompt_financial_analyst_agent"
    temperature: 0
    agent_name: "financial_analyst"
